version: '3'
services:
  app:
    container_name: cook_app
    build: .
    ports:
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - mysql # This service depends on postgres. Start that first.
      # - mysql # This service depends on mysql. Start that first.
    networks:
      - cook_network
  mysql:
     image: mysql:5.7
     ports:
       - 3306:3306
     environment:
       - MYSQL_DATABASE=${DB_NAME}
       - MYSQL_USER=${DB_USER}
       - MYSQL_PASSWORD=${DB_PASSWORD}
       - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
       - DATABASE_HOST=${DB_HOST}
     volumes:
       - database_mysql:/var/lib/mysql/data
     networks:
       - cook_network

volumes:
  api:
  database_mysql:

# Networks to be created to facilitate communication between containers
networks:
  cook_network:

